// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGC4JXkywtgoLBXtISCbQKHpVZM3YcJUQ',
    appId: '1:274658383295:web:aa7076ae69196f9d6dfd0a',
    messagingSenderId: '274658383295',
    projectId: 'pingmeet-e5822',
    authDomain: 'pingmeet-e5822.firebaseapp.com',
    storageBucket: 'pingmeet-e5822.firebasestorage.app',
    measurementId: 'G-LQM6TNGXRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2o_TrWkCuRjK619IZHsquhbSq9a9PVxQ',
    appId: '1:274658383295:android:8c41beb9df67ab726dfd0a',
    messagingSenderId: '274658383295',
    projectId: 'pingmeet-e5822',
    storageBucket: 'pingmeet-e5822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNlM0nHoTKu20KxgoGJ1QW_bk6rW7DUEA',
    appId: '1:274658383295:ios:5a0ac437d531333a6dfd0a',
    messagingSenderId: '274658383295',
    projectId: 'pingmeet-e5822',
    storageBucket: 'pingmeet-e5822.firebasestorage.app',
    iosBundleId: 'com.example.pingmeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNlM0nHoTKu20KxgoGJ1QW_bk6rW7DUEA',
    appId: '1:274658383295:ios:5a0ac437d531333a6dfd0a',
    messagingSenderId: '274658383295',
    projectId: 'pingmeet-e5822',
    storageBucket: 'pingmeet-e5822.firebasestorage.app',
    iosBundleId: 'com.example.pingmeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGC4JXkywtgoLBXtISCbQKHpVZM3YcJUQ',
    appId: '1:274658383295:web:fb11ef76d60788346dfd0a',
    messagingSenderId: '274658383295',
    projectId: 'pingmeet-e5822',
    authDomain: 'pingmeet-e5822.firebaseapp.com',
    storageBucket: 'pingmeet-e5822.firebasestorage.app',
    measurementId: 'G-7HF1VDT4Q9',
  );
}
